"""
PDF Report Generator
Uses ReportLab (BSD license) to produce a clean analysis report.
"""

from pathlib import Path
from datetime import datetime
from core.aggregator import AggregatedResult
from detectors.base import MediaType


def export_pdf_report(result: AggregatedResult, source_file: str, output_path: str):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except ImportError:
        raise RuntimeError("reportlab is not installed. Run: pip install reportlab")

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                 fontSize=20, spaceAfter=4, textColor=colors.HexColor("#1a1a1a"))
    story.append(Paragraph("Deepfake Detection Report", title_style))

    sub_style = ParagraphStyle("Sub", parent=styles["Normal"],
                               fontSize=10, textColor=colors.HexColor("#8a8a8a"), spaceAfter=12)
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", sub_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e8e8e6")))
    story.append(Spacer(1, 8 * mm))

    # File info
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"],
                                   fontSize=13, spaceAfter=6, textColor=colors.HexColor("#1a1a1a"))
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                fontSize=10, textColor=colors.HexColor("#333333"), leading=16)

    story.append(Paragraph("File Information", heading_style))
    file_data = [
        ["File", Path(source_file).name],
        ["Path", str(source_file)],
        ["Media Type", result.media_type.value.capitalize()],
        ["File Size", _format_size(Path(source_file).stat().st_size)],
    ]
    story.append(_table(file_data))
    story.append(Spacer(1, 8 * mm))

    # Overall verdict
    story.append(Paragraph("Overall Verdict", heading_style))
    risk_color = {"low": "#27ae60", "medium": "#e67e22", "high": "#c0392b"}.get(result.risk_level, "#1a1a1a")
    verdict_data = [
        ["Deepfake Score", f"{result.score_pct}%"],
        ["Verdict", result.verdict],
        ["Confidence", f"{result.confidence_pct}%"],
        ["Threshold Used", f"{round(result.threshold * 100)}%"],
        ["Flagged", "Yes" if result.flagged else "No"],
    ]
    story.append(_table(verdict_data, highlight_row=1, highlight_color=risk_color))
    story.append(Spacer(1, 8 * mm))

    # Key Findings
    if result.key_findings:
        story.append(Paragraph("Key Findings", heading_style))
        for i, finding in enumerate(result.key_findings):
            bullet_style = ParagraphStyle(
                "Bullet", parent=styles["Normal"],
                fontSize=10, textColor=colors.HexColor("#333333"),
                leading=16, leftIndent=12,
                spaceAfter=4,
            )
            prefix = "▸  " if i > 0 else "⬛  "
            story.append(Paragraph(f"{prefix}{finding}", bullet_style))
        story.append(Spacer(1, 6 * mm))

    # Module results
    story.append(Paragraph("Module Results", heading_style))
    module_rows = [["Module", "Score", "Confidence", "Verdict"]]
    for r in result.module_results:
        if not r.supported:
            module_rows.append([r.module_name, "N/A", "N/A", "Not applicable"])
        elif r.error:
            module_rows.append([r.module_name, "Error", "—", r.error[:40]])
        else:
            module_rows.append([
                r.module_name,
                f"{round(r.score * 100)}%",
                f"{round(r.confidence * 100)}%",
                r.label,
            ])
    story.append(_module_table(module_rows))
    story.append(Spacer(1, 8 * mm))

    # Disclaimer
    disc_style = ParagraphStyle("Disc", parent=styles["Normal"],
                                fontSize=9, textColor=colors.HexColor("#aaaaaa"), leading=14)
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e8e8e6")))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "This report is generated by Deepfake Detector (open-source, MIT license). "
        "Results are probabilistic and should not be used as sole evidence of authenticity or manipulation. "
        "Always combine with human expert review for high-stakes decisions.",
        disc_style,
    ))

    doc.build(story)


def _format_size(size_bytes: int) -> str:
    if size_bytes > 1024 * 1024:
        return f"{size_bytes / 1024 / 1024:.1f} MB"
    return f"{size_bytes / 1024:.1f} KB"


def _table(data: list, highlight_row: int | None = None, highlight_color: str = "#1a1a1a"):
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors

    t = Table(data, colWidths=[55 * 3.779528, 120 * 3.779528 / 10])
    style = [
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#8a8a8a")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1a1a1a")),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#fafafa")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e8e8e6")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]
    t.setStyle(TableStyle(style))
    return t


def _module_table(data: list):
    from reportlab.platypus import Table, TableStyle
    from reportlab.lib import colors

    t = Table(data, colWidths=["45%", "12%", "15%", "28%"])
    style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a1a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#ffffff"), colors.HexColor("#fafafa")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e8e8e6")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]
    t.setStyle(TableStyle(style))
    return t
